### PR TITLE
add support for jumping shell buffers #55

### PR DESCRIPTION
**Pull request by jacktasia**
As discussed in #55

### CODE REVIEW

**Comment by jacktasia** [comment]
@zenspider This seems to work for me. Can you give this a try a let me know if you have any feedback before I merge?

**Comment by jacktasia** [comment]
When running from a shell buffer, it will first check for a `.dumbjump` file in the project root with a line containing just `language X` (like `language python`, `language Ruby` - there should only be one). If that doesn't exist then, it will attempt to guess based on the file extensions it finds in the buffer contents. Right now the latter is problematic if you do `ls` in a directory with lots of different extensions, as it could accidently use the wrong language.

**Comment by zenspider** [comment]
I wasn't sure how to test this properly as I currently have it installed via package. I used `curl` to replace the file and then bytecompiled it. It isn't working for me tho, as I'm currently getting: `"Please save your file before jumping."` in response to using it in `M-x shell`.

**Comment by jacktasia** [comment]
@zenspider Sorry, here's some instructions:

1.  Select all copy/paste the [new code here](https://raw.githubusercontent.com/jacktasia/dumb-jump/47077940e891b21b8a13ea63744f95e541866c6b/dumb-jump.el) into a fresh buffer in emacs 
2. <kbd>M-x</kbd> `eval-buffer` on the buffer with the new code.

Please let me know if you still have problems. Thanks.

**Pull request merged**
