### PR TITLE
Fixed C++ function regexp for template arguments (#87)

### PR DESCRIPTION
**Pull request by netromdk**
I fixed C++ function regexp for template arguments and added a few C++ tests.

Test file "test/data/proj1/src/cpp/issue-87.cpp" verifies the fix of issue #87.

"Ran 106 tests, 106 results as expected (2017-03-10 23:06:41+0100)"

### CODE REVIEW

**Comment by jacktasia** [comment]
Thanks for the PR! it looks like the `dumb-jump-cpp-issue87` test is failing on TravisCI though (looks like it's still going to the commented section there). Ideas?

**Comment by netromdk** [comment]
You're welcome. It's weird because when I run `make test` locally then all tests pass just fine. Hmm.

**Comment by jacktasia** [comment]
I just re-triggered the jobs on Travis just in case. What OS are you running locally?

**Comment by netromdk** [comment]
I'm running macOS 10.12.3 (16D32) using Emacs 25.1.1

**Comment by jacktasia** [comment]
Interesting. I am on macOS 10.11.6 using Emacs 25.1 and running your changes locally I get the same as TravisCI.

**Comment by jacktasia** [comment]
I wonder if it's a difference in `ag`/`rg` versions?

**Comment by netromdk** [comment]
I'm running:

> % ag --version
> ag version 1.0.2
> 
> Features:
>   +jit +lzma +zlib

> % rg --version
> 0.2.3

And I can see that TravisCI is using a way older version: 0.30

**Comment by jacktasia** [comment]
This is what I have:

```
$ rg --version
ripgrep 0.3.1
$ ag --version
ag version 1.0.2
```

**Comment by netromdk** [comment]
Could you try executing the following command in the root of the repo and see that you get the same result?

screen shot 2017-03-11 at 00 01 22

**Comment by jacktasia** [comment]
image

**Comment by netromdk** [comment]
Very weird. At its core, the fix consisted of changing `[,&*.]` into `[,&*.<>]`, which is a perfectly valid regular expression.

**Comment by netromdk** [comment]
Inside Emacs if I apply the change, byte-compile, load the library, and execute `dump-jump-go` at the same place as the test (inside "issue-87.cpp") then it lands at the correct place.

Could you try the same?

**Comment by jacktasia** [comment]
> Inside Emacs if I apply the change, byte-compile, load the library, and execute dump-jump-go at the same place as the test (inside "issue-87.cpp") then it lands at the correct place.

It still jumped to the commented version for me. I see how your change fixes the regex so it shows up on the list when it didn't before, but it's not stopping the commented version from showing up (both of our screenshots show a match for it).

If anything it seems like it's a bug with how I am parsing the ag response lines since the expected winner is split across multiple lines, which I think is making it ignore it...especially since I tried a test where I just ignored any code that started with `//` and then it basically kept reporting it couldn't find any matches.

**Comment by netromdk** [comment]
What's interesting is that on my machine the sorted `(match-sorted (-sort (lambda (x y) (< (plist-get x :diff) (plist-get y :diff))) results))` yields the correct result before the wrong one:

> type: "" | jump? (:path "MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp" :line 6 :context "CAdaptiveCaching::_processPixelOverlap(const CHitInfoLite &hit," :diff 11 :target "_processPixelOverlap") | matches: ((:path "MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp" :line 6 :context "CAdaptiveCaching::_processPixelOverlap(const CHitInfoLite &hit," :diff 11 :target "_processPixelOverlap") (:path "MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp" :line 2 :context "//  CAdaptiveCaching::_processPixelOverlap()" :diff 15 :target "_processPixelOverlap")) | sorted: ((:path "MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp" :line 6 :context "CAdaptiveCaching::_processPixelOverlap(const CHitInfoLite &hit," :diff 11 :target "_processPixelOverlap") (:path "MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp" :line 2 :context "//  CAdaptiveCaching::_processPixelOverlap()" :diff 15 :target "_processPixelOverlap")) | results: ((:path "MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp" :line 2 :context "//  CAdaptiveCaching::_processPixelOverlap()" :diff 15 :target "_processPixelOverlap") (:path "MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp" :line 6 :context "CAdaptiveCaching::_processPixelOverlap(const CHitInfoLite &hit," :diff 11 :target "_processPixelOverlap"))

As far as I can see, because the `:diff 11` < `:diff 15`?

**Comment by netromdk** [comment]
Now it disregards results with a context starting with the one-line comment of the given language of the current file. From the debug info you can see that "sort-no-comments" only contains the one match we are interested in:

> type: "" | 
> jump? (:path "MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp" :line 6 :context "CAdaptiveCaching::_processPixelOverlap(const CHitInfoLite &hit," :diff 11 :target "_processPixelOverlap") | 
> matches: ((:path "MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp" :line 6 :context "CAdaptiveCaching::_processPixelOverlap(const CHitInfoLite &hit," :diff 11 :target "_processPixelOverlap")) | 
> sorted-no-comments: ((:path "MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp" :line 6 :context "CAdaptiveCaching::_processPixelOverlap(const CHitInfoLite &hit," :diff 11 :target "_processPixelOverlap")) | 
> results: ((:path "MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp" :line 2 :context "//  CAdaptiveCaching::_processPixelOverlap()" :diff 15 :target "_processPixelOverlap") (:path "MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp" :line 6 :context "CAdaptiveCaching::_processPixelOverlap(const CHitInfoLite &hit," :diff 11 :target "_processPixelOverlap"))

**Comment by jacktasia** [comment]
Interesting. If you uncomment the `NORMAL RUN` debug `prin1`. Can you confirm what searcher you're using? I somehow missed this yesterday, but currently `rg` will win over `ag` (if they're both installed) and last we commented our `rg` versions were different, which must explain the situation.

**Comment by netromdk** [comment]
It uses `ag`:
```
NORMAL RUN: CMD ’"ag --nocolor --nogroup --cc --cpp --ignore-dir /ignored --ignore-dir /ignored2 \\\\b_processPixelOverlap\\(\\\\s\\|\\\\\\)\\)\\*\\\\\\(\\(\\\\w\\|\\[\\,\\&\\*.\\<\\>\\]\\|\\\\s\\)\\*\\(\\\\\\)\\)\\\\s\\*\\(const\\|-\\>\\|\\\\\\{\\|\\$\\)\\|typedef\\\\s\\+\\(\\\\w\\|\\[\\(\\*\\]\\|\\\\s\\)\\+_processPixelOverlap\\(\\\\\\)\\|\\\\s\\)\\*\\\\\\(\\|\\\\b\\(\\?\\!\\(class\\\\b\\|struct\\\\b\\|return\\\\b\\|else\\\\b\\|delete\\\\b\\)\\)\\(\\\\w\\+\\|\\[\\,\\>\\]\\)\\(\\[\\*\\&\\]\\|\\\\s\\)\\+_processPixelOverlap\\\\s\\*\\(\\\\\\[\\(\\\\d\\|\\\\s\\)\\*\\\\\\]\\)\\*\\\\s\\*\\(\\[\\=\\,\\(\\)\\{\\;\\]\\|\\:\\\\s\\*\\\\d\\)\\|\\#define\\\\s\\+_processPixelOverlap\\\\b\\|\\\\b\\(class\\|struct\\|enum\\|union\\)\\\\b\\\\s\\*_processPixelOverlap\\\\b\\\\s\\*\\(final\\\\s\\*\\)\\?\\(\\:\\(\\(\\\\s\\*\\\\w\\+\\\\s\\*\\:\\:\\)\\*\\\\s\\*\\\\w\\*\\\\s\\*\\<\\?\\(\\\\s\\*\\\\w\\+\\\\s\\*\\:\\:\\)\\*\\\\w\\+\\>\\?\\\\s\\*\\,\\*\\)\\+\\)\\?\\(\\(\\\\\\{\\|\\$\\)\\)\\|\\}\\\\s\\*_processPixelOverlap\\\\b\\\\s\\*\\; MASKED_OUT/git/dumb-jump/test/data/proj1"’ RESULTS: "MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp:2://  CAdaptiveCaching::_processPixelOverlap()
MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp:6:CAdaptiveCaching::_processPixelOverlap(const CHitInfoLite &hit,
MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp:7:                                       const float *directIllum,
MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp:8:                                       const float  thresholdElevation,
MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp:9:                                       TContribArray &carray,
MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp:10:                                       CRCOctree<TRecord> *octree)
MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp:11:{
"
   passed   11/106  dumb-jump-cpp-issue87
```

I only have `rg` installed so all tests will pass btw. But I personally prefer `ag`.
I'm setting up a Linux VM and seeing if things are different there.

**Comment by netromdk** [comment]
Running `rg` on the Linux VM I can confirm it only finds the first and incorrect match:

> NORMAL RUN: CMD '"rg --color never --no-heading --line-number --type c --type cpp -g \\!/ignored -g \\!/ignored2 \\\\b_processPixelOverlap\\(\\\\s\\|\\\\\\)\\)\\*\\\\\\(\\(\\\\w\\|\\[\\,\\&\\*.\\\\\\\\\\<\\\\\\\\\\>\\]\\|\\\\s\\)\\*\\(\\\\\\)\\)\\\\s\\*\\(const\\|-\\>\\|\\\\\\{\\|\\$\\)\\|typedef\\\\s\\+\\(\\\\w\\|\\[\\(\\*\\]\\|\\\\s\\)\\+_processPixelOverlap\\(\\\\\\)\\|\\\\s\\)\\*\\\\\\(\\|\\\\b\\(class\\|struct\\|enum\\|union\\)\\\\b\\\\s\\*_processPixelOverlap\\\\b\\\\s\\*\\(final\\\\s\\*\\)\\?\\(\\:\\(\\(\\\\s\\*\\\\w\\+\\\\s\\*\\:\\:\\)\\*\\\\s\\*\\\\w\\*\\\\s\\*\\<\\?\\(\\\\s\\*\\\\w\\+\\\\s\\*\\:\\:\\)\\*\\\\w\\+\\>\\?\\\\s\\*\\,\\*\\)\\+\\)\\?\\(\\(\\\\\\{\\|\\$\\)\\)\\|\\}\\\\s\\*_processPixelOverlap\\\\b\\\\s\\*\\; MASKED_OUT/git/dumb-jump/test/data/proj1"' RESULTS: "MASKED_OUT/git/dumb-jump/test/data/proj1/src/cpp/issue-87.cpp:2://  CAdaptiveCaching::_processPixelOverlap()
"

**Comment by netromdk** [comment]
Btw I just found out that `rg` doesn't support multiline matching!  And `ag` does. See [here](https://github.com/BurntSushi/ripgrep#why-shouldnt-i-use-ripgrep):

> ripgrep doesn't have multiline search. (Unlikely to ever be supported.)

I would suggest making `ag` the default tool when available because it supports multiline searches. What do you think? With that in place then my pull request will pass. Thanks.

**Comment by jacktasia** [comment]
> I would suggest making ag the default tool when available because it supports multiline searches. What do you think?

Sounds good to me. I am going to merge this now. Thanks for all the work on this!

**Pull request merged**
