### PR TITLE
Add Rust support.

### LINKED ISSUE #35: Add rustlang support
It would be great to have rust support

### PR DESCRIPTION
**Pull request by meqif**
Hi!

This pull request adds support for Rust files and would close #35.

I apologise in advance for some of the hairier regular expressions. If someone could suggest more efficient or cleaner alternatives, I would be grateful. If not, that's also okay.

### CODE REVIEW

**Comment by jacktasia** [comment]
Awesome! Thanks for doing this. This looks good to me. Just give me a bit to try it out for real and then I'll merge it. Thanks again!

**Comment by meqif** [comment]
Thank you. 😄 
I noticed a small mistake (a "test" instead of "JJJ" in a regular expression). I'll fix that in a jiffy and push a new squashed commit.

**Comment by meqif** [comment]
I see no more obvious mistakes and the commit was pushed, feel free to merge.

**Comment by meqif** [comment]
Awesome, thanks for merging!

**Comment by jacktasia** [comment]
Of course! :shipit: Thanks again for adding Rust support. FWIW your changes should be available via MELPA in 3-12 hours.

**Pull request merged**
