### PR TITLE
readme: Update language list of supported languages

### PR DESCRIPTION
**Pull request by nxtr**
Added Apex from #391 to supported language list, and cross-checked and added some more, please review.
Now, totals 55 langs, great stuff !

### CODE REVIEW

**Comment by phikal** [comment]
The commentary section in dumb-jump.el should probably also be updated.

**Comment by phikal** [comment]
Oops, I forgot to mention the [header](https://github.com/jacktasia/dumb-jump/blob/master/dumb-jump.el#L1), that should also be updated. Sorry about that.

**Review by jacktasia — COMMENTED** [review]
Thanks!

**Review by jacktasia — APPROVED** [review]
Sorry, was waiting for the GitHub Action to run but they're stuck, although not really required for this change.

**Comment by nxtr** [comment]
> Sorry, was waiting for the GitHub Action to run but they're stuck, although not really required for this change.

Yeah, I suspected the action needed a kick. Great stuff !

**Pull request merged**
