### PR TITLE
Implemented support for git grep (#34)

### PR DESCRIPTION
**Pull request by netromdk**
Can be used by setting `(setq dumb-jump-searcher "git-grep")`.

Also added test cases.

### CODE REVIEW

**Comment by netromdk** [comment]
The coverage decreased because travis doesn't have git grep installed when running the tests.

**Comment by jacktasia** [comment]
Wow! Thanks for the PR!

> The coverage decreased because travis doesn't have git grep installed when running the tests.

I think if we add `git-all` to the [end of this line](https://github.com/jacktasia/dumb-jump/blob/master/.travis.yml#L5) so it's `sudo apt-get install -y silversearcher-ag git-all` instead it might work.

**Comment by jacktasia** [comment]
Hmm, TravisCI didn't seem to like `git-all` I guess we should just try `git` instead.

**Comment by netromdk** [comment]
Totally agree :)

**Comment by netromdk** [comment]
@jacktasia finally! Hehe.

**Comment by jacktasia** [comment]
Awesome! Thanks!

**Pull request merged**
