### PR TITLE
Added Fsharp support

### PR DESCRIPTION
**Pull request by walseb**

### CODE REVIEW

**Comment by jacktasia** [comment]
Thanks for the PR! It looks like the `rg` tests are failing. If you don't want to fix them for `rg` it's totally fine to just drop `rg` from the `:supports` block. Thanks again!

**Comment by walseb** [comment]
That's really weird because `rg --type-list` returns `fsharp: *.fs, *.fsi, *.fsx`.
Anyway, I'm removing support for it like you suggested.

**Comment by walseb** [comment]
Oh yeah, the problem could also be that rg has some special regex rule. Anyway rg support isn't that important to me.

**Comment by walseb** [comment]
Oh, I forgot to remove some other rg support flags, fixing

**Pull request merged**
