### PR TITLE
Improved ci

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Setting up coverage :)

Do you want me to create the melpa recipe?

### CODE REVIEW

**Comment by jacktasia** [comment]
Thanks for doing this! Just out of curiosity how did you find this so quickly? Thanks for the offer on the melpa recipe but there's a few things I want to clean up first.

**Comment by AdrieanKhisbe** [comment]
I KNOW EVERYTHING ^^
haha. I didn't remember, I had to dig a bit.

It was because of this tweet: https://twitter.com/github_el/status/684940247701032960

**Comment by AdrieanKhisbe** [comment]
<shamelessPromoting>
In case, https://github.com/AdrieanKhisbe/cask-package-toolset.el.

But not that needed since you have already CI setted up :D
thus might help you for badge and melpa recipe
</shamelessPromoting>

**Comment by jacktasia** [comment]
Interesting, I didn't know about that twitter account. Thanks for the heads up. I might need to use your https://github.com/AdrieanKhisbe/cask-package-toolset.el because the code coverage stuff doesn't seem to be going through with how it is now.

**Comment by AdrieanKhisbe** [comment]
ha wait, you need to login with your github account to activate coveralls.

**Comment by jacktasia** [comment]
Right, I've already done that:

image

...and I've done a couple of commits since then but I still don't see anything there. Unclear what, if anything, else I have to do.

**Comment by AdrieanKhisbe** [comment]
mmmmmm

**Comment by AdrieanKhisbe** [comment]
strange

**Comment by AdrieanKhisbe** [comment]
I think I know. 
You are testing on compiled code. right?

**Comment by jacktasia** [comment]
Ohhh, yeah it does look like I am. Most of the testing boilerplate I've been borrowing from other projects. Looks like I'll need to make some tweaks to get the code coverage stuff working.

**Comment by AdrieanKhisbe** [comment]
undercover doesn't work with compiled code.
Have a look to the one shippped with cpt:
https://github.com/AdrieanKhisbe/cask-package-toolset.el/blob/master/Makefile

**Comment by jacktasia** [comment]
Thanks. I switched up the Makefile and the ci testing is still working correctly, but still nothing on the code coverage.

**Comment by AdrieanKhisbe** [comment]
Might be the extra `(require 'dumb-jump)` in test/dumb-jump-test.el

(you should move all the require in the `test-helper.el`, that is called before each of test file

**Comment by jacktasia** [comment]
Tried a bunch of different things none of them seem to have worked. I am going to give up on this for now, but will happily accept any PRs related to it. I want to spend time on the other features I want to get done before doing the melpa recipe. Thanks!

**Comment by AdrieanKhisbe** [comment]
Will try to have a look tomorrow. :)

**Comment by jacktasia** [comment]
I finally got it to send to coveralls! Thanks for all your help!

**Comment by AdrieanKhisbe** [comment]
De rien =)

**Pull request merged**
