### PR TITLE
misc minor cleanups

### PR DESCRIPTION
**Pull request by wbolster**

### CODE REVIEW

**Comment by netromdk** [comment]
That seems like an incredible small reason for a pull request.

**Comment by wbolster** [comment]
dear @netromdk,

thank you for your warm and welcoming comment.

behaviour like this totally pisses me off and i am writing this to tell you why.

first, some context. i was looking at this project's code when having a first stab at #131, after @jacktasia encouraged me to proceed by giving a positive reply to my proposal. while doing so, i noticed a grammar mistake in one of the docstrings, so i decided to fix it right away. i also noticed a byte compilation warning that can be easily avoided, so i fixed that as well. i realised these two changes have nothing to do with #131, so i pushed them to another branch and quickly opened a pr. i decided to roll those two unrelated changes up into a single pr to reduce overhead.

and that's when you stepped in to show off your _asshole_ skills:

> That seems like an incredible small reason for a pull request.

well done. apparently you think my contribution is not valuable because it is a small one. and the message you are sending here is that you think i am wasting your time. actually, what you are also implying is that i am wasting my own time.

think of it. instead of just not replying at all, you actually take time to tell random strangers on the internet that their contribution to an open source project (which is not even run by you) is too trivial to be worth doing.

so to make it absolutely clear: you are telling others that you think what they are doing is useless, but apparently doing so is a valuable way of spending your own time. go figure what that tells about yourself. does it make you feel good? because it certainly makes others feel bad.

so here we are. instead of ignoring your unsollicited negative comment or silently walking away to never come back, i am writing you this [public response to your negative behavior](https://opensource.guide/building-community/), because i have [zero tolerance for assholes](https://jacobian.org/writing/assholes/) and i will not [settle for assholes](https://okdistribute.xyz/post/okf-de). i am glad you are not the maintainer of this project because you would surely have scared me away never to return to your project, because [when you are not cordial, i will be on my way](https://www.kennethreitz.org/essays/be-cordial-or-be-on-your-way).

once you're done reading the articles i linked in the previous paragraph, let's make it a bit more practical for you, because i suspect you may need just that.

as an example, let's take a look at [evil-commentary](https://github.com/linktohack/evil-commentary), which is one of many emacs packages i use daily. at some point, someone submitted [a pr to fix an emacs compiler warning](https://github.com/linktohack/evil-commentary/pull/11), and here is [another one by me that does the same](https://github.com/linktohack/evil-commentary/pull/15), which of course was also welcomed. experiences like that are what prompts me to proceed with more substantial contributions, such as [my rewrite of the project's readme](https://github.com/linktohack/evil-commentary/pull/17). actually, sometimes [just saying thanks](https://github.com/Dewdrops/evil-exchange/issues/10) is a good contribution.

i do that because i also like it a lot when other people contribute to my own projects. people send me emails just to say thanks. sometimes they even [send me money](https://happybase.readthedocs.io/en/latest/). i appreciate those gestures, also if it is ‘just’ [fixing a link](https://github.com/wbolster/argskwargs/pull/1), [fixing a typo](https://github.com/wbolster/happybase/pull/140), or [fixing markup](https://github.com/wbolster/evil-colemak-basics/pull/4). and even when i do not agree, [i can still be friendly](https://github.com/wbolster/jsonlines/pull/24).

hopefully you realise that your behaviour is detrimental to open source in general, and i strongly urge you to not behave like this again because it upsets people, as you can see.

oh, and if you were thinking of writing a response, make sure that you start with something along the lines of ‘sorry, i did not realise i was being such a jerk, thank you for pointing that out to me’.

kind regards,

@wbolster

**Comment by netromdk** [comment]
All I can say is wow, and it says much more about you than me. 😊

**Comment by wbolster** [comment]
instead of replying with nonsense within a few minutes, please read it again, and actually read the linked articles (which you clearly did not). and maybe then write a response. or not.

**Comment by jacktasia** [comment]
Thanks

**Comment by wbolster** [comment]
since it seems @jacktasia removed some heated comments from this pr (presumably because he does not want to be the host of a discussion that he has no part in, which i can partly get into), here's the original content:

https://gist.github.com/wbolster/c7ae7fc48177a62df2a3764b4e89b14c

https://twitter.com/wbolster/status/860941403869908992

/cc @netromdk

**Comment by jacktasia** [comment]
@wbolster

Please read this [Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md)

I appreciate your PR. I don't care that it was small, but it was objectively small. People are allowed to have opinions about that. His comment wasn't mean or hostile. It wasn't exactly nice, and I can understand why you didn't like it, but your response was mean and hostile. You assumed a lot from his comment.

The [Code of Conduct lists examples of good and bad behavior](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md#our-standards). You could have used the first set of examples to handle the comment you didn't like, but you used the second set. You made personal attacks and _now_ I feel like you're publically harassing him by advertising this.

Please be "respectful of differing viewpoints and experiences" and  "focus on what is best for the community" by dropping this. It started as a simple miscommunication by people that have different working styles. You escalated it by assuming a lot of things. I'd appreciate it if you'd just delete any references to this (and I will delete this comment), but if after reading that Code Of Conduct you stand by your behavior then we can just agree to disagree.

**Comment by wbolster** [comment]
(fyi, everything currently online is anonymised with the only personal references left pointing to me.)

let me explain.

overall my open source experience (15+ years) has been pretty positive, which is what keeps me doing this.

but not everything is smooth. on the contrary. people send me angry emails demanding that i work to fix their problems for free. people question my motivations. people expect me to read their minds and treat me as stupid because i ask questions. others send very demotivating one-liners to random strangers on the internet, out of the blue, for no reason, which serves absolutely no purpose except hurting others, which is exactly what happened with this pr.

this happens more often than is good for me. that leaves me with a few options:

- tolerate/ignore it. this means i silently support things that i wholeheartedly disagree with. that's a no for me.

- no longer participate myself. this is giving in to the bad minority. i like open source. it's a hobby of mine. i won't have others decide what are my hobbies. so that's a no for me.

- call people out for their negative behaviour, which is what i did.

it seems the only way to make people aware that i (and many others, see e.g. articles i linked in my rant) find their behaviour disturbing for our community. tolerating/ignoring bad behaviour does not change anyone. "do not read the comments" works as long as one is just a "consumer", but when one is actively contributing/producing, there is no way around this.

yes, that sometimes means throwing dirt back. yes, i use a pejorative (inspired by one of the linked articles in my rant). that is because as a long term open source contributor and maintainer i experienced way too much negativity towards things that i do in my spare time to help others, for free. i am done with this and will no longer tolerate any of it.

(sorry to drag you into this.)

**Pull request merged**
