### PR TITLE
Jl support

### PR DESCRIPTION
**Pull request by AShedko**
Some changes
* made types searchable
* added some function decorators

response for this
https://github.com/jacktasia/dumb-jump/issues/159

SIde note:
Does spacemacs lag behind melpa, as the changes are not awailable there?

### CODE REVIEW

**Comment by jacktasia** [comment]
Awesome, thanks!

> Does spacemacs lag behind melpa, as the changes are not available there?

I honestly don't use spacemacs, so I am not sure, but it could be:

1. There is a spacemacs julia layer and it doesn't load dumb-jump for its keybindings?
2. They use a mirror of MELPA that runs behind?

or maybe something else. if you can confirm the correct version of dumb-jump is installed _after_ you upgrade (the only way I know to check is: <kbd>M-x</kbd> `package-list-packages-no-fetch`) then it's potentially number 1 and we may want to consider creating an  issue with spacemacs.

**Comment by AShedko** [comment]
Apparently they use version 2017.08.21.13 .

**Comment by jacktasia** [comment]
> Apparently they use version 2017.08.21.13 .

[It doesn't look like they pin versions yet]( https://github.com/syl20bnr/spacemacs/issues/2057). Have you tried upgrading `dumb-jump` manually? Try <kbd>M-x</kbd> `package-refresh-contents` then `package-list-packages` the on that buffer <kbd>U</kbd> (shift+u) then <kbd>x</kbd>

**Comment by AShedko** [comment]
I got the latest version. Thank you. unfortunately i had no luck actually using the module as i keep getting
`julia declaration not found` errors.

**Comment by jacktasia** [comment]
>  unfortunately i had no luck actually using the module as i keep getting `julia declaration not found` errors.

Sorry, it didn't work. Could you please provide more information about your setup? 

- OS
- shell
- searcher (ag, grep, etc), 
- debug output (setting `(setq dumb-jump-debug t)` and then trying a jump and checking `*Messages*`)
- example of code you're jumping from/to
- check if another searcher works (`(setq dumb-jump-force-searcher 'ag)` See README)

This will help me track down where it's failing for you.

**Comment by AShedko** [comment]
OS: GNU/Linux (Fedora 25) [Linux localhost.localdomain 4.12.8-200.fc25.x86_64 #1 SMP Thu Aug 17 15:39:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux]
shell: zsh
searcher: ag
debug output:
`

cmd: 
	ag --nocolor --nogroup --julia --jl \(\@noinline\|\@inline\)\?\\s\*function\\s\*subplot_data\\s\*\\\(\|const\\s\+subplot_data\\b\|\(mutable\)\?\\s\*struct\\s\*subplot_data\|\(type\|immutable\|abstract\)\\s\*subplot_data /home/ashedko/.julia/v0.6/Gadfly
raw results: 
	ag: unrecognized option '--jl'
Usage: ag [FILE-TYPE] [OPTIONS] PATTERN [PATH]
...

-----
DUMB JUMP DEBUG ‘dumb-jump-run-command‘ END
-----
`
setting `grep` as the searcher works.

**Comment by jacktasia** [comment]
The `ag: unrecognized option '--jl'` is telling us the problem. 

My bad for not catching this in the PR, but you overrode the [existing](https://github.com/jacktasia/dumb-jump/blob/master/dumb-jump.el#L864) `jl` extension rule with bad [rg](https://github.com/BurntSushi/ripgrep/blob/master/ignore/src/types.rs#L149) and [ag](https://github.com/ggreer/the_silver_searcher/blob/master/tests/list_file_types.t#L141) types.

Fixed in https://github.com/jacktasia/dumb-jump/commit/5aa56feecfe38971d9ede687eebf6346dc85758a

Thanks for getting me the debug details so fast.

**Comment by AShedko** [comment]
Glad to help, I think I`ll add some more regexes for function declaration syntax.

**Pull request merged**
