### PR TITLE
Added search argument options for each search tool

### PR DESCRIPTION
**Pull request by DeeeeLAN**
Hi, I took a stab at adding the search arguments myself. I made the git-grep one from yesterday more generic, and added options for ag and rg.

### CODE REVIEW

**Comment by DeeeeLAN** [comment]
Sorry this took a little churn. I don't have cask locally.

**Comment by jacktasia** [comment]
Thanks for opening this! I think `dumb-jump-git-grep-search-untracked` needs to stay as a boolean option for backwards compatitlity with people's configuration since it has existed for a while. Although I agree that `dumb-jump-git-grep-search-args` can replace `dumb-jump-git-grep-search-untracked-args` to just become a totally new feature. Thoughts?

**Comment by DeeeeLAN** [comment]
Yeah I guess we don't want to break anybody's code. I can update it tomorrow or you can take care of it now, whatever works.

**Comment by jacktasia** [comment]
Okay, cool. I pushed up a commit with the changes I think make sense. I'll probably merge this sometime tomorrow unless you see anything else you think should change. Thanks again!

**Comment by DeeeeLAN** [comment]
That looks good to me, I just fixed a couple comments you missed. I noticed that there is a git-grep+ag function- I don't know if it makes sense to add any flags from either or both tools to that function or not.

**Comment by jacktasia** [comment]
> I just fixed a couple comments you missed.

Great, thanks!

> I noticed that there is a git-grep+ag function- I don't know if it makes sense to add any flags from either or both tools to that function or not.

Yeah, this is a specialized/experimental searcher for developing on the linux kernel (#250 / #254) that I don't think needs to be updated for this (yet).

**Pull request merged**
