### PR TITLE
Add nix support

### PR DESCRIPTION
**Pull request by terlar**
This is very basic, but nix is also a very basic language. Everything is basically variables (definitions) and they could be either data or functions.

The recommended way to find definitions got me to think about this:
https://nixos.wiki/wiki/Nix_Expression_Language#Finding_a_.28function.2Fpackage.2F.E2.80.A6.29_definition

I haven't tested this much yet, but seems to work.

### CODE REVIEW

**Comment by jacktasia** [comment]
Thanks for the PR! It looks like the tests are failing for `grep` and `git-grep`. I can dig in more after work today.

**Comment by terlar** [comment]
Yes, I saw that too, haven't had time to look at it yet either. Sorry about that. Yes please, if you have time. Otherwise I will look at it later today or tomorrow :)

**Comment by jacktasia** [comment]
Ah, it's because you have a `\n` in the test and `grep` and `git-grep` do not support multi-line matching. I pushed a fix into your branch. Please let me know what you think.

**Comment by terlar** [comment]
Ah, that explains it. I think that is fine, I personally don't use that, but perhaps it would be neat to have support for them as well. I am not sure if the match needs to be like that or if the match should just be on the definition line ending with equals might be okay. As long as it would work for definitions with the value on the next line

**Comment by terlar** [comment]
Thank you! For the assistance and a great package. Will try to get cask installed until next time so I could run the tests and make a more complete PR. :)

**Pull request merged**
