### PR TITLE
[WIP] Add coffeescript support

### PR DESCRIPTION
**Pull request by jonboiser**
#28 

This is a work in progress, starting with the regex for functions.

### CODE REVIEW

**Comment by jacktasia** [comment]
Awesome! Let me know if you have any questions.

**Comment by jacktasia** [comment]
@jonboiser I am a bit confused by the `[WIP]`, is this ready to merge as far as you're concerned?

**Comment by jonboiser** [comment]
WIP == 'Work in progress'. I still need to write rules for variables and classes/types

**Comment by jonboiser** [comment]
What is the benefit of setting `:type` in the plist? When I test out these rules,

```
foo = () => 1
foo = 1

foo()
console.log foo
```

it doesn't seem to differentiate between the types when I jump. Is there a way of telling that `foo()` should jump to `foo` (type is function)?

**Comment by jacktasia** [comment]
Great question. `type` is mainly used with `dumb-jump-language-contexts`, so it would know that `foo()` should only jump to a function definition.

**Comment by jonboiser** [comment]
I'm not sure why my tests are failing. I've been testing them here https://regex101.com/r/kZ6xM8/1.

I'm assuming these are perl-compatible regex?

**Comment by jacktasia** [comment]
> I'm assuming these are perl-compatible regex?

They are for `ag`,  but not `grep` since not all versions of `grep` support `-P` (only `-E`).  Since most people use dumb-jump with `ag`, I would just not bother supporting `grep` if I was you. That is, switch from `:supports ("ag" "grep")` to just `:supports ("ag")` for your rules.

**Comment by jonboiser** [comment]
@jacktasia I think this is ready for review. I've been testing it out on this script

https://gist.github.com/jonboiser/955fc16d8aa2803c550726396d3852bc

The language contexts thing looks really powerful, but might be left for a later day, so this PR just has basic rules.

Also, I noticed that rules in other languages still jump to commented code. I disallowed that in my rules, but had to duplicate that logic. Maybe a future feature will be to define rules for comments, and have the searcher ignore such strings?

**Comment by jacktasia** [comment]
>  I think this is ready for review. I've been testing it out on this script

Cool. Thanks for doing this. I'll take a closer look tonight, but this looks pretty good.

> Maybe a future feature will be to define rules for comments, and have the searcher ignore such strings?

This is an interesting idea. In practice, I haven't run into this, but I certainly understand the appeal for certain projects. Feel free to make a new issue for it so that a discussion can get started if others agree. 

Thanks!

**Pull request merged**
